FROM public.ecr.aws/lambda/python:3.11

# Install dependencies
COPY ResumeTrigger/requirements.txt .
RUN pip install -r requirements.txt

# Enable CloudWatch logging for production
ENV ENABLE_CLOUDWATCH=TRUE

# Copy code
COPY ResumeTrigger/ /var/task/ResumeTrigger

# Lambda uses this automatically, no entrypoint override
CMD ["ResumeTrigger.lambda_function.lambda_handler"]